const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const CONCERT_NAME="Rajesh Krishnan";
const GFORM_URL=""; // paste your Google Form link here
$("#cname").innerHTML=CONCERT_NAME.split("").map((c,i)=>`<span style="--i:${i}">${c===" "?"&nbsp;":c}</span>`).join("");
const IC={search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',briefcase:'<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2M3 13h18"/>',commerce:'<path d="M3 3v18h18"/><path d="m7 15 4-4 3 3 5-6"/><path d="M15 8h4v4"/>',gaming:'<rect x="2" y="7" width="20" height="11" rx="5"/><path d="M7 10v5M4.5 12.5h5"/><circle cx="16" cy="11.5" r=".8"/><circle cx="18.5" cy="14" r=".8"/>',eye:'<circle cx="12" cy="12" r="3"/><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/>',phone:'<path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/>',instagram:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".6"/>',youtube:'<rect x="2.5" y="5" width="19" height="14" rx="4"/><path d="m10 9 5 3-5 3z"/>',pin:'<path d="M12 21s7-6.2 7-11.5A7 7 0 0 0 5 9.5C5 14.8 12 21 12 21z"/><circle cx="12" cy="9.5" r="2.5"/>',code:'<path d="m8 8-5 4 5 4M16 8l5 4-5 4M14 5l-4 14"/>',palette:'<path d="M12 3a9 9 0 1 0 0 18c1.500 0 2-1 1.500-2-.5-1 0-2 1.500-2H17a4 4 0 0 0 4-4c0-5-4-10-9-10z"/><circle cx="7.500" cy="11" r="1"/><circle cx="10" cy="7" r="1"/><circle cx="15" cy="7" r="1"/>',chev:'<path d="m6 9 6 6 6-6"/>',download:'<path d="M12 3v12m0 0-4-4m4 4 4-4M4 21h16"/>',music:'<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',dance:'<circle cx="12" cy="4.5" r="2"/><path d="M12 7v6l-3 5M12 13l3 5M5 9l7-2 6 3"/>',culture:'<path d="M3 5h11v6a5.5 5.5 0 0 1-11 0z"/><path d="M10 15a5.5 5.5 0 0 0 11-4V8h-5"/><path d="M6 8.5h1M10 8.5h1M6.5 11.5c1 1 2.5 1 3.5 0"/>',sports:'<path d="M8 4h8v5a4 4 0 0 1-8 0zM8 6H4v2a3 3 0 0 0 4 3M16 6h4v2a3 3 0 0 1-4 3M12 13v4M8 21h8M10 17h4"/>',star:'<path d="m12 3 2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M3 10h18M8 3v4M16 3v4"/>',mic:'<rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3"/>'};
const ico=n=>`<i class="ico">${'<svg viewBox="0 0 24 24">'+IC[n]+'</svg>'}</i>`;
$$("[data-ic]").forEach(e=>e.innerHTML='<svg viewBox="0 0 24 24">'+IC[e.dataset.ic]+'</svg>');
const RULES=["Bring your college ID","Report 30 minutes before your slot","Judges' decision is final"];
const CATS=[
{n:"Technical",ic:"code",t:"Code, debug and build.",ev:[
 {"n": "Tech Treasure Hunt", "a": "", "t": "2–3 members per team", "f": ["₹200", ""], "d": "4 Nov 2026", "tm": "10:00 AM – 1:00 PM", "v": "Computer Laboratory (PB1, PB2, PB3)", "fc": ["Asst. Prof. Gagan"], "x": [["Duration", "120 minutes"]], "r": ["##Task", "Each team will receive a starting folder on the computer containing multiple files and subfolders. Teams must solve a series of technical clues, each leading to the next, to eventually reach the Final Treasure.", "##Rules and regulations", "Each team must have 2–3 members, who must stay together throughout the event.", "The event must be completed within the given time. No extra time will be given.", "Participants must maintain discipline and must not disturb other teams.", "Mobile phones, AI tools and external help are not allowed.", "Participants must not damage, modify, delete or access unauthorised files or systems.", "Sharing answers or helping other teams is not allowed. Cheating may lead to disqualification.", "Participants must follow the organisers’ instructions. The organisers’ decision will be final."], "sc": ["Lucky Jain"]},
 {"n": "Code Relay", "a": "", "t": "3 members per team", "f": ["₹200", ""], "d": "4 Nov 2026", "tm": "2:00 PM – 4:00 PM", "v": "Computer Laboratory (PB1, PB2, PB3)", "fc": ["Asst. Prof. Lavanya"], "x": [["Duration", "90 minutes"]], "r": ["##Round 1 – Code Relay (20 minutes)", "Each team will receive one answer sheet. Team members must take turns answering on the same sheet.", "Student 1 – 5 minutes", "Student 2 – 5 minutes", "Student 3 – 10 minutes", "Only the student whose turn it is may write on the answer sheet.", "The final student must submit the answer sheet.", "##Round 2 – Debug Relay (50 minutes)", "Teams will receive programs containing hidden bugs and must debug them in a relay format.", "Student 1 – Programming Problem 1 (15 minutes)", "Student 2 – Programming Problem 2 (15 minutes)", "Student 3 – Programming Problem 3 (20 minutes)", "Each participant will be given a fixed time for their turn.", "##Rules and regulations", "The order of participants cannot be changed once the event begins.", "Each participant must complete their turn within the given time limit.", "After completing their turn, a participant cannot return to the computer or the answer sheet.", "Participants must not communicate, use gestures or show their code/answers to teammates during another participant’s turn.", "The next participant must continue from the work left by the previous participant.", "Internet, AI tools, mobile phones and external assistance are not allowed.", "Only the final submitted answer/code will be evaluated. Multiple answers will not be considered.", "The final code must be submitted within the allotted time and must pass the required test cases."], "sc": ["Rahul Singh"]},
 {"n": "Live Deploy Race", "a": "", "t": "2 members per team", "f": ["₹200", ""], "d": "5 Nov 2026", "tm": "9:00 AM – 12:00 PM", "v": "Computer Laboratory (PB1, PB2, PB3)", "fc": ["Asst. Prof. Pooja"], "x": [["Duration", "2 hours"]], "r": ["##Task (1 hour 30 minutes)", "Every team will receive the same broken web application as a ZIP file. Teams must:", "Identify the problems in the application.", "Fix all the identified issues.", "Deploy the corrected application.", "Submit the live URL of the deployed application.", "##Rules and regulations", "Each team must consist of 2 members.", "The task must be completed within the given time.", "Teams must work only on their assigned system and must not copy or share code with other teams.", "The use of AI tools, external assistance or pre-built project files is not permitted.", "Internet access may be used only for resources specifically permitted by the organisers (for deployment only).", "The decision of the organisers/judges will be final."], "sc": ["Monish"]},
 {"n": "Gen AI Cinema", "a": "", "t": "2–3 members per team", "f": ["₹100", ""], "d": "4 Nov 2026", "tm": "9:00 AM – 1:00 PM", "v": "3rd Floor, BCA Department (LH-1)", "fc": ["Asst. Prof. Priya K"], "x": [["Duration", "2 hours"], ["Video duration", "4–5 minutes"]], "r": ["##Task", "Teams will receive a surprise theme and must create a short cinematic video based on it.", "The story and concept must be developed during the competition.", "AI tools may be used for the script, images, video, voice, music and sound effects.", "Video editing software may be used.", "The final video must be 4–5 minutes long.", "The final submission must be in MP4 format.", "##Rules and regulations", "Each team must consist of 2–3 members.", "Wi-Fi and PCs/laptops will not be provided.", "All creative work must be completed during the competition.", "Previously created videos, completed projects or another team’s content must not be used.", "Movie/TV clips, copyrighted videos, images, music, songs, dialogues and other copyrighted content must not be used.", "Offensive, hateful, sexually explicit, illegal or inappropriate content is strictly prohibited.", "The final video must be submitted before the deadline, along with the team details and the AI tools used.", "The decision of the organisers/judges will be final."], "sc": ["Zenkar"]},
 {"n": "De_Code", "a": "", "t": "2–3 members per team", "f": ["₹200", ""], "d": "5 Nov 2026", "tm": "2:00 PM – 5:00 PM", "v": "Computer Laboratory (PB1, PB2, PB3)", "fc": ["Asst. Prof. Ayesha"], "x": [["Duration", "180 minutes"]], "r": ["##Rounds", "Round 1 – Easy level (20 minutes)", "Round 2 – Moderate level (30 minutes)", "Round 3 – Hard level (40 minutes)", "##Task", "Teams will receive 3–5 input–output examples of an unknown program. Teams must:", "Study the input and output.", "Identify the pattern.", "Write the program.", "Compile and test the solution.", "Submit the final program.", "Judges will use hidden test cases for evaluation.", "##Rules and regulations", "Each team must consist of 2–3 members.", "Teams must complete all rounds within the allotted time.", "Teams may use only the programming language and tools specified by the organisers.", "Internet, AI tools and external assistance are not permitted.", "Teams must not share code or solutions with other teams.", "The submitted program must pass the hidden test cases used by the judges.", "Only the final submitted program will be considered for evaluation.", "The judges’ decision will be final in case of any dispute."], "sc": ["Shahid Ali"]},
 {"n": "Tech Arena", "a": "", "t": "2–3 members per team", "f": ["₹200", ""], "d": "5 Nov 2026", "tm": "9:00 AM – 1:00 PM", "v": "3rd Floor, BCA Department (LH-1)", "fc": ["Asst. Prof. Nanda T"], "x": [["Number of teams", "15"], ["Duration", "60 minutes"]], "r": ["##Task", "Three bowls will contain Easy, Moderate and Hard technical tasks.", "Teams can pick a task from any bowl.", "Each difficulty level carries different marks.", "Teams must solve the task and submit the solution to the co-ordinator/evaluator.", "If the solution is correct, the team can pick the next task.", "Teams can change a task up to 3 times if they are unable to solve it.", "Marks will be deducted for each abandoned task, and it cannot be selected again.", "The team with the highest score within 60 minutes wins.", "##Rules and regulations", "Each team must have 2–3 members.", "The total time for the event is 60 minutes.", "Teams can choose tasks from any difficulty bowl.", "Internet, AI tools and external assistance are not allowed.", "Teams can change a task up to 3 times.", "Marks will be deducted for abandoned tasks, and the same task cannot be selected again.", "Only correctly solved and submitted tasks will receive marks.", "The team with the highest score will be declared the winner.", "The organisers’ decision will be final in case of any dispute."], "sc": ["Prajwal Gowda"]}]},
{n:"Cultural",ic:"culture",t:"Stage, rhythm and style.",ev:[
 {"n": "Group Dance", "a": "A vibrant group dance competition where teams come together to showcase their talent, creativity, coordination, and passion for dance. Participants can explore different dance styles and entertain the audience through energetic and captivating performances.", "t": "Minimum 4 participants per team", "f": ["₹1,000", "per team"], "d": "4 Nov 2026", "tm": "10:30 AM onwards", "fc": [["Asst. Prof. Gayathri Rao N", "9742072583"], ["Asst. Prof. Hema R", "9742048383"]], "sc": [["Aditi K", "9620225616"], ["Akshatha BN", "6361635459"]], "r": ["Each team must consist of a minimum of 4 participants.", "The performance duration is 5+2 minutes.", "A maximum of 2 non-participants is allowed for assistance.", "Green room facilities will be provided for participants.", "Participants must submit their music in a pen drive at the registration desk.", "Vulgarity or inappropriate performances are strictly prohibited.", "Participants must maintain discipline and follow the event coordinators' instructions.", "The decision of the judges and organizers shall be final and binding."]},
 {"n": "Solo Dance", "a": "A platform for solo performers to express their individuality, creativity, and passion through dance. This competition celebrates the art of movement, where every participant gets the opportunity to take the stage, captivate the audience, and showcase their unique style. From powerful performances to graceful expressions, let every step make a statement.", "t": "Individual", "f": ["₹300", "per participant"], "d": "4 Nov 2026", "tm": "10:30 AM onwards", "fc": [["Asst. Prof. Gayathri Rao N", "9742072583"], ["Asst. Prof. Hema R", "9742048383"]], "sc": [["Aditi K", "9620225616"], ["Akshatha BN", "6361635459"]], "r": ["The competition is open to individual participants only.", "The performance duration is 4+2 minutes.", "One non-participant is allowed to assist each participant.", "Green room facilities will be provided for participants.", "Participants must submit their music in a pen drive at the registration desk.", "Vulgarity or inappropriate content in the performance is strictly prohibited.", "The decision of the judges and organizers shall be final and binding."]},
 {"n": "Group Singing", "a": "A lively group singing competition that brings together voices, creativity, and teamwork on one stage. Participants can showcase their vocal talent, blend their voices in harmony, and create a memorable musical experience for the audience. Whether it’s a soulful melody or an energetic performance, let your team’s harmony take the spotlight!", "t": "Minimum 3 participants per team", "f": ["₹400", "per team"], "d": "5 Nov 2026", "tm": "10:00 AM onwards", "fc": [["Asst. Prof. Gayathri Rao N", "9742072583"], ["Asst. Prof. Vidhya S", "9482919788"]], "sc": [["Aadya A", "9742972699"], ["Ashwithaa", "8123460406"]], "r": ["Each team must consist of a minimum of 3 participants.", "The performance duration is 4+1 minutes.", "A maximum of 2 non-participants is allowed to assist each team.", "Karaoke tracks are allowed for the performance.", "Any equipment or performance element requiring electricity is not permitted.", "Participants must submit their karaoke/audio track at the registration desk beforehand.", "Vulgarity or inappropriate content is strictly prohibited.", "Green room facilities will be provided for participants.", "The decision of the judges and organizers shall be final and binding."]},
 {"n": "Solo Singing", "a": "A platform for solo singers to step into the spotlight and showcase their unique voice, confidence, and musical expression. Participants can choose their preferred song and create a memorable performance through their vocals, style, and stage presence. Let your voice take center stage and leave a lasting impression!", "t": "Individual", "f": ["₹200", "per participant"], "d": "5 Nov 2026", "tm": "10:00 AM onwards", "fc": [["Asst. Prof. Gayathri Rao N", "9742072583"], ["Asst. Prof. Hema R", "9742048383"]], "sc": [["Aadya A", "9742972699"], ["Ashwithaa", "8123460406"]], "r": ["The competition is open to individual participants only.", "The performance duration is 3+1 minutes.", "Karaoke tracks are allowed for the performance.", "Participants must submit their karaoke/audio track at the registration desk as instructed by the organizers.", "Any equipment or performance element requiring electricity, other than the facilities provided by the organizers, is not permitted.", "Vulgarity or inappropriate content in the lyrics or performance is strictly prohibited.", "Green room facilities will be provided for participants.", "The decision of the judges and organizers shall be final and binding."]},
 {"n": "Fashion Show", "a": "Step onto the runway and bring your creativity, confidence, and style to life! It’s a team-based fashion show where participants showcase their unique concepts through fashion, music, styling, and coordinated performances. With creativity meeting confidence, every team gets the opportunity to make a statement on the runway.", "t": "Minimum 6 participants per team", "f": ["₹2,000", "per team"], "d": "5 Nov 2026", "tm": "12:30 PM onwards", "fc": [["Asst. Prof. Ulekha Jain", "8861739365"], ["Asst. Prof. Vidhya S", "9482919788"]], "sc": [["Aditi K", "9620225616"], ["Akshatha BN", "6361635459"]], "r": ["Each team must consist of a minimum of 6 participants.", "The performance duration is 6+2 minutes.", "A maximum of 2 non-participants is allowed to assist each team.", "Green room facilities will be provided for participants.", "Teams must submit their video and audio tracks at the time of registration.", "The theme, costumes, music, and presentation must be appropriate for a college event.", "Participants are responsible for arranging their costumes, accessories, and other required materials.", "The decision of the judges and organizers shall be final and binding."]}
]},
{n:"Management",ic:"briefcase",t:"Think, pitch and lead.",ev:[
 {"n": "IPL Auction", "g": "Bid Premier League", "s": "Bid, build and win with a fixed budget.", "a": "Bid Premier League is a strategic bidding game where teams compete to build their strongest cricket squad within a fixed budget. Players are introduced with base prices, and teams bid against each other to acquire them. Success depends on smart budgeting, player selection, strategy, and teamwork.", "t": "4 members per team", "f": ["₹400", "per team"], "d": "5 Nov 2026", "tm": "10:00 AM", "v": "2nd Floor, BBA Department (Room No: LHS - 7)", "fc": ["Asst. Prof. Lishanth", "9900242060"], "sc": ["Diganth", "7483094982"], "r": ["Registration Fee: ₹400 per team.", "Each team must consist of 4 members.", "Final 10 teams would be selected for the bidding round.", "Participants must report to the venue 30 minutes before the event begins.", "In detailed rules will be communicated on the day of the event.", "The decision of the Auction Committee and organising committee shall be final and binding."]},
 {"n": "The Court of Four", "g": "Dice and Destiny", "s": "A giant live Chowka Bara board game.", "a": "The Dice And Destiny is a fun, interactive team game that combines the traditional Chowka Bara board game with exciting challenges. Participants become the game pieces and move across a giant board based on their dice throw. Each box contains a different task or challenge. Complete the challenges, reach the final destination, and be the first team to win the game!", "t": "2 members per team", "f": ["₹200", "per team"], "d": "4 & 5 Nov 2026", "tm": "10:00 AM", "v": "2nd Floor, BBA Department (Room No: LHS - 4 and PU Quadrangle)", "fc": ["Asst. Prof. Lishanth", "9900242060"], "sc": ["Jeevan", "9916396115"], "r": ["Registration Fee: ₹200 per team.", "Each team must consist of 2 members.", "Participants must report to the venue 30 minutes before the event begins.", "In detailed rules will be communicated on the day of the event.", "The decision of the organising committee shall be final and binding."]},
 {"n": "Billion Dollar Stuff", "g": "Billionaire's Code", "s": "A high-energy business strategy challenge.", "a": "Billionaire's code is a high-energy team challenge that puts your business instincts, strategy, decision-making and confidence to the test. With unexpected situations, limited information and choices that could change everything, every move matters.", "t": "3 members per team", "f": ["₹300", "per team"], "d": "4 Nov 2026", "tm": "11:00 AM", "v": "2nd Floor, BBA Department (Room No: LHS - 3)", "fc": ["Asst. Prof. Tejaswini", "8792887774"], "sc": ["Mounya", "9900128355"], "r": ["Registration Fee: ₹300 per team.", "Each team must consist of 3 members.", "Participants must report to the venue 30 minutes before the event begins.", "In detailed rules will be communicated on the day of the event.", "Use of mobile phones and electronic gadgets is strictly prohibited during the event.", "The decision of the organising committee shall be final and binding."]},
 {"n": "Rebranding", "g": "Brand Alchemy", "s": "A marketing and branding challenge.", "a": "Brand Alchemy is an exciting marketing and branding challenge that puts your creativity, strategic thinking, consumer understanding and communication skills to the test. Participants will be challenged to look beyond the obvious, create impactful ideas and turn them into something that can capture attention.", "t": "2 members per team", "f": ["₹300", "per team"], "d": "5 Nov 2026", "tm": "10:00 AM", "v": "2nd Floor, BBA Department (Room No: LHS - 3)", "fc": ["Asst. Prof. Annapurna", "9740962089"], "sc": ["Tanisha", "8310898456"], "r": ["Registration Fee: ₹300 per team.", "Each team must consist of 2 members.", "Participants must report to the venue 30 minutes before the event begins.", "Each team must carry their own laptops, phones & necessary gadgets.", "Participants may use Canva, PowerPoint, posters, AI or a simple pitch deck where permitted for the campaign round.", "In detailed rules will be communicated on the day of the event.", "The decision of the judging panel and organising committee shall be final and binding."]},
 {"n": "Best Manager", "g": "Corporate Catalyst", "s": "Think, lead and respond to the unexpected.", "a": "Corporate Catalyst is a dynamic management challenge designed to test how participants think, communicate, lead and respond when faced with unexpected situations. The competition will push participants beyond conventional management concepts and place them in situations where judgement, adaptability, confidence and leadership matter.", "t": "Individual", "f": ["₹300", "per participant"], "d": "5 Nov 2026", "tm": "10:00 AM", "v": "2nd Floor, BBA Department (Room No: LHS - 2)", "fc": ["Asst. Prof. Anupama", "8095295370"], "sc": ["Mounya", "9900128355"], "r": ["Registration Fee: ₹300 per participant.", "Corporate Catalyst is an individual competition.", "Participants must report to the venue 30 minutes before the event begins.", "The competition will consist of multiple rounds, and participants may be eliminated based on their performance.", "The use of mobile phones, smart devices, internet or other external assistance are restricted.", "In detailed rules will be communicated on the day of the event.", "The decision of the judging panel and organising committee shall be final and binding."]},
 {"n": "Escape Room", "g": "The Great Escape", "s": "Solve clues and escape before time runs out.", "a": "Step into a world of mystery, clues and unexpected challenges. Work together, observe carefully, solve puzzles and connect the hidden clues to uncover the path to escape. With limited time and every detail potentially holding a secret, only teamwork, logic, observation and quick thinking can lead you to the final answer.", "t": "2 members per team", "f": ["₹200", "per team"], "d": "4 & 5 Nov 2026", "tm": "10:00 AM", "v": "2nd Floor, BBA Department (Room No: LHS - 1)", "fc": ["Asst. Prof. Lishanth", "9900242060"], "sc": ["Ramya", "9035493036"], "r": ["Registration Fee: ₹200 per team.", "Each team must consist of 2 members.", "Participants must report to the venue 30 minutes before the event begins.", "No mobile phones, internet, AI, or external assistance.", "In detailed rules will be communicated on the day of the event.", "The decision of the organising committee shall be final and binding."]},
 {"n": "Commodity Auction", "g": "Trade Titans", "s": "Read the market and win the auction.", "a": "Enter a high-stakes marketplace where instinct, strategy and smart decision-making come together. Trade Titans challenges participants to read the market, seize opportunities and make every move count. With an unpredictable game environment and competition that keeps you on your toes, only those who can think ahead, adapt quickly and play smart will stand out.", "t": "3 members per team", "f": ["₹300", "per team"], "d": "4 Nov 2026", "tm": "11:00 AM", "v": "2nd Floor, BBA Department (Room No: LHS - 7)", "fc": ["Asst. Prof. Lishanth", "9900242060"], "sc": ["Manish", "8217458461"], "r": ["Registration Fee: ₹300 per team.", "Each team must consist of 3 members.", "Participants must report to the venue 30 minutes before the event begins.", "Use of mobile phones and other electronic gadgets is strictly prohibited during the event. Calculators may be used only for calculation purposes.", "In detailed rules will be communicated on the day of the event.", "The decision of the Auction Committee and organising committee shall be final and binding."]}]},
{n:"Commerce",ic:"commerce",t:"Money, markets and trade.",ev:[
 {"n": "Treasure Hunt", "t": "3 members per team", "fc": ["Asst. Prof. Suma G", "+91 99646 87819"], "sc": ["Koushaliya", "9113640529"], "r": ["##General rules", "Entry Fee: Rs.400", "Each team must consist of 3 members.", "Teams must register before the event begins.", "All teams will start from the same designated starting point.", "Each team will receive its own clues/instructions.", "Teams must solve the clues and proceed to the designated checkpoints.", "All 3 members must stay together throughout the hunt.", "Teams must complete the required puzzles and activities at each checkpoint.", "Teams must follow the clues in the order given.", "Teams must not take, move, hide, or damage clues meant for other teams.", "Following another team to discover a location or answer is not allowed.", "Taking help from people outside the team is not permitted.", "Hints may be requested from the organisers, subject to the applicable time penalty.", "Mobile phones may be used only when permitted by the organisers.", "Running is not allowed during the event.", "Teams must not enter restricted or unauthorised areas.", "Teams must not disturb regular college activities or other participants.", "The timer will stop only after the team successfully completes the final task and reaches the designated finish point.", "Any penalties will be added to the team's final time.", "The team with the lowest adjusted completion time will be declared the winner.", "The organisers' decision will be final in case of disputes."], "a": "", "d": "5 Nov 2026", "tm": "11:00 AM", "v": "College ground", "f": ["₹400", "per team"]},
 {"n": "Product Launch", "t": "2 members per team", "fc": ["Asst. Prof. Vasanth Praveen", "9916147721"], "sc": ["Savithri", "6363079286"], "r": ["##General rules", "Entry Fee: Rs.500", "Each team must consist of exactly 2 members.", "Both members must actively participate in all four rounds.", "Teams cannot replace members once the competition begins.", "Use of phones/internet will not be permitted unless specifically allowed by the organizers.", "No plagiarism or copying of another team's concept.", "Teams must not disturb or communicate with other teams during preparation.", "Any misconduct may result in disqualification.", "Judges' decisions will be final and binding.", "Participants must report 10–15 minutes before the event."], "a": "", "d": "4 Nov 2026", "tm": "2:30 PM – 5:00 PM", "v": "LH F1, LH F3 and LH F4", "f": ["₹500", "per team"]},
 {"n": "Scary House", "fc": ["Asst. Prof. Ruchika & Asst. Prof. Anala", "+91 63603 64897"], "sc": ["Nithin", "6362639746"], "r": ["##Rules and regulations", "Entry Fee: Rs.300 Team of 3", "🚫 No Running", "🚫 No Pushing Or Fighting", "🚫 Do Not Touch The Actors", "🚫 Do Not Damage Props Or Decorations", "🚫 No Food, Drinks, Smoking Or Vaping", "🚫 No Abusive Or Inappropriate Behaviour", "📵 Photography/Recording May Be Restricted", "##Safety first", "Follow all instructions given by organizers and volunteers.", "Emergency exits must remain clear.", "If you feel dizzy, uncomfortable, or unwell, inform a volunteer immediately.", "Participants with medical conditions that may be affected by intense scares, flashing lights, or loud sounds should avoid the attraction.", "Physical contact between actors and participants is not permitted unless specifically approved as part of a safe activity."], "a": "", "d": "4 & 5 Nov 2026", "tm": "11:00 AM", "v": "LH B1 and B2", "f": ["₹300", "per team of 3"], "t": "3 members per team"},
 {"n": "Dog Show", "fc": ["Asst. Prof. Manoj Kumar", "+91 98449 81772"], "sc": ["Dheeraj", "8660062901"], "r": ["##Rules and regulations", "Each Dog Must Be Registered Before The Event Starts.", "Entry Fee: Adult Dog: Rs.600 & Puppy Dog: Rs.400", "Aggressive Or Untrained Dogs Will Not Be Allowed.", "Vaccination Certificate Is Compulsory.", "Handler Must Present Their Dog When Announced.", "Judgement Will Be Based on Breed's Standard.", "Owners Are Responsible for Their Dogs Throughout The Event.", "Any Misconduct or Rule Violation Will Lead to Disqualification.", "Keep The Area Clean and Dispose of Waste Properly.", "Dogs Must Run and Pose Within the Designated Track Area."], "a": "", "d": "5 Nov 2026", "tm": "11:00 AM", "v": "College Ground", "f": ["Adult ₹600 · Puppy ₹400", "per dog"]},
 {"n": "Biz-Quiz", "t": "2 members per team", "fc": ["Asst. Prof. Sowmya G.S & Asst. Prof. Lathshree", "+91 99862 57167"], "sc": ["Varun", "9019061209"], "r": ["##Team formation and guidelines", "Team Size: Each team must consist of 2 members.", "Registration fee: Rs. 500", "Substitution: Replacement of team members is not allowed once the competition has started.", "Authority: The decision of the Quizmaster will be final.", "##Round 1: Preliminary (MCQ round)", "Format: 40 Multiple Choice Questions (MCQs).", "Time Allotted: 20 minutes.", "Selection: Qualification for the next round is based on performance.", "Connectivity: Participants must ensure stable internet connectivity on their devices.", "##Round 2: Semi-final", "Format: 30 Multiple Choice Questions.", "Time Allotted: 30 minutes.", "Marking: No negative markings.", "Tie/Participant Adjustment: Sub-rounds will be introduced if the number of participants exceeds anticipation.", "##Round 3: Final (open rapid-fire round)", "System: A bidding system will be introduced.", "Format: Rapid-fire questionings.", "##General rules", "Punctuality: Teams must report at least 15 minutes before the start of each round.", "Restrictions: Use of books or any external assistance is strictly prohibited.", "Tie-Breaker: In case of a tie, tie-breaker questions will be asked.", "Discipline: In case of cheating, organizers reserve the right to disqualify the team.", "Final Authority: The decision of the organizers will be final and binding."], "a": "", "d": "4 Nov 2026", "tm": "11:00 AM", "v": "LH G2 and LH F6", "f": ["₹500", "per team"]},
 {"n": "Beg, Borrow, Steal", "t": "4 members per team", "fc": ["Asst. Prof. Manjushri U & Asst. Prof. Vandana", "+91 78990 05164"], "sc": ["Charan KP", "8073662264"], "r": ["##Team formation", "Each team must consist of 4 members.", "Registration fee: Rs.500", "All team members must belong to a registered college/institution and carry their valid College ID cards.", "Swapping or replacing team members after the event begins is strictly prohibited.", "##Game play and objective", "Teams will be given a list of items at the start of the event.", "The goal is to collect as many items from the list as possible within the specified time limit.", "Items must be brought back to the submission venue before the timer runs out. Late submissions will face point deductions or disqualification.", "##Permitted actions and restrictions", "Begging & Borrowing: Participants can beg or borrow items from anyone inside the campus (faculty, students, non-teaching staff, visitors).", "\"Stealing\" (Simulated): Stealing is meant purely in a fun, non-malicious spirit. However, no actual theft, destruction, or damage to property is allowed.", "Prohibited Items: You cannot steal/take personal wallets, official college records, emergency equipment, or cash without permission.", "Buying items using money (purchasing from campus canteens or shops) is strictly NOT allowed.", "##Safety and conduct guidelines", "Campus Boundaries: Participants must remain within the designated campus boundaries. Leaving the campus premises will lead to immediate disqualification.", "No Force or Misbehavior: Physical force, harassment, arguing, or misbehaving with anyone on campus will result in instant disqualification.", "Safety First: Running safely and respecting campus rules (avoiding restricted areas like exam halls or laboratories) is mandatory.", "##Scoring and judging criteria", "The team with the highest total points within the time limit wins.", "In case of a tie: the team that reported earlier gets priority, OR a tie-breaker task will be assigned by the organizers.", "Final Authority: The decision of the event organizers and judges will be final and binding."], "a": "", "d": "4 Nov 2026", "tm": "11:00 AM", "v": "College Ground", "f": ["₹500", "per team"]},
 {"n": "Rocket League", "fc": ["Asst. Prof. Kiran", "99161 47721"], "sc": ["Sambram VR", "9742751683"], "r": ["Entry Fee: Rs.600", "It's a knockout format.", "Time of 6 min divided into 2 halves each.", "Own goal considered is counted as opponent goal.", "In case of tie breaker, first team to score in the extra time wins.", "If both the teams fail to score even after the extra time, previous matches score will be taken for consideration."], "a": "", "d": "5 Nov 2026", "tm": "2:30 PM – 5:00 PM", "v": "LH F1", "f": ["₹600", ""]},
 {"n": "Mock Stock", "t": "2 members per team", "fc": ["Asst. Prof. Divya", "+91 81056 38861"], "sc": ["Darshan H P", "9844152160"], "r": ["##General rules and guidelines", "Each team must consist of 2 members.", "Registration Fee: Rs.500", "Participants must carry their own mobile phone/laptop.", "Participants are responsible for maintaining stable internet connectivity.", "Teams must strictly follow the time limit given for each round.", "Any form of unfair practice, external assistance, or unauthorized tools will lead to disqualification.", "Decisions taken by the event coordinators/judges will be final.", "Participants must follow the instructions given by the coordinators throughout the event.", "Any attempt to manipulate the platform, data, or results will result in immediate disqualification.", "The rules may be modified by the organizers if required, and participants will be informed accordingly."], "a": "", "d": "5 Nov 2026", "tm": "9:00 AM", "v": "LH G2", "f": ["₹500", "per team"]}]},
{n:"Gaming",ic:"gaming",t:"Play, compete and win.",ev:[
 {"n": "BGMI", "a": "", "t": "4 players per team", "f": ["₹400", ""], "d": "4 Nov 2026", "tm": "10:00 AM – 2:00 PM", "v": "3rd Floor, BCA Department (LH-4 to LH-7)", "fc": [["Asst. Prof. Chetan"], ["Asst. Prof. Yashwanth"]], "x": [], "r": ["Each team must consist of 4 players.", "Team members may belong to any college.", "Players must produce their physical ID cards at the time of registration. Players who fail to do so will not be permitted to participate.", "The tournament will be conducted in a league format, with 3 matches in total.", "Maps: Erangel and Miramar.", "Points will be allotted for placement (e.g. 1st place = 20 points, 2nd place = 16 points).", "Each kill will be awarded 1 point.", "The teams with the highest total points will be placed 1st, 2nd and 3rd.", "Players must use their own internet connection."]},
 {"n": "Free Fire", "a": "", "t": "4 players per team", "f": ["₹400", ""], "d": "5 Nov 2026", "tm": "9:00 AM – 2:00 PM", "v": "3rd Floor, BCA Department (LH-4 to LH-7)", "fc": [["Asst. Prof. Chetan"], ["Asst. Prof. Yashwanth"]], "x": [], "r": ["Each team must consist of 4 players.", "Players must produce their physical ID cards at the time of registration. Players who fail to do so will not be permitted to participate.", "Map: Bermuda.", "The use of a VPN is not permitted.", "PC players are not allowed.", "If any participant is caught using game bugs or hacks, the whole team will be disqualified.", "Every custom lobby will be hosted by the college.", "Gun Property will remain off.", "Character skills will remain on.", "Teaming up is not allowed in full-map matches.", "All rounds will be conducted on an elimination basis.", "Players must use their own internet connection."]}]},
{n:"Creative Arts",ic:"palette",t:"Colour, lines and imagination.",ev:[
 {n:"Mehndi",s:"Intricate henna designs on a given theme.",a:"Create a mehndi design on a given theme. Cones are provided by participants.",t:"Individual"},
 {n:"Face Painting",s:"Turn a face into a canvas.",a:"Paint a theme-based design on your partner's face using safe, skin-friendly colours.",t:"Pair"},
 {n:"Sketching",s:"Pencil and charcoal drawing on the spot.",a:"Sketch a subject announced on the spot. Bring your own pencils and drawing tools.",t:"Individual"},
 {n:"Digital Art",s:"Create artwork on screen with your own tools.",a:"Produce digital artwork on a given theme using software of your choice.",t:"Individual"}]}];
const SCH=(()=>{const T=x=>{const m=/(\d+):(\d+)\s*(AM|PM)/i.exec(x||"");if(!m)return 9999;let h=+m[1]%12;if(/pm/i.test(m[3]))h+=12;return h*60+ +m[2]};
 const days={1:[],2:[],3:[]};
 days[1].push({t:"9:00 AM",n:"Inauguration",s:"Lamp lighting and welcome"});
 days[3].push({t:"6:30 PM",n:"Live concert",s:"Rajesh Krishnan performs live · closing"});
 CATS.forEach(c=>c.ev.forEach(e=>{if(!e.d||!e.tm)return;const st=(/\d+:\d+\s*[AP]M/i.exec(e.tm)||[e.tm])[0].trim();
  (e.d.split("Nov")[0].match(/\d+/g)||[]).forEach(n=>{const k=+n-3;if(days[k])days[k].push({t:st,n:e.n,c:c.n,s:[e.tm,e.v].filter(Boolean).join(" · ")})})}));
 const out={};for(const k in days){const g={};days[k].forEach(x=>(g[x.t]=g[x.t]||[]).push(x));out[k]=Object.keys(g).sort((a,b)=>T(a)-T(b)).map(t=>[t,g[t]])}return out})();
const SP=["Title Sponsor","Powered By","Associate Partner","Media Partner","Food Partner","Tech Partner","Travel Partner","Fashion Partner"];
$("#t1").innerHTML=[...SP,...SP].map(s=>`<span>${s}</span>`).join("");
$("#t2").innerHTML=[...SP].reverse().concat([...SP].reverse()).map(s=>`<span>${s}</span>`).join("");

const flat=CATS.flatMap(c=>c.ev);
$("#cats").innerHTML=CATS.map((c,i)=>`<div class="rv ${['l','','r'][i%3]}" style="--d:${i*.12}s"><button class="cat" data-cat="${i}" aria-expanded="false" aria-controls="subwrap">${ico(c.ic)}<h3>${c.n}</h3><span class="n">${c.ev.length} events</span><span class="hint"><b class="hint-t" data-m="Click to open" data-t="Tap to open" data-mc="Click to close" data-tc="Tap to close"></b><span class="chev">${ico('chev')}</span></span></button></div>`).join("");
let openC=-1;
const evCard=(i,k,n)=>{const e=CATS[i].ev[k];return `<div class="sub" style="--i:${n??k}">${e.g?`<small>${e.g.toUpperCase()}</small>`:""}<h4>${e.n}</h4>${e.f?`<div class="feetag">Entry fee ${e.f[0]} <span>${e.f[1]}</span></div>`:""}${e.d?`<div class="evdt"><div><i>Date</i><b>${e.d}</b></div>${e.tm?`<div><i>Time</i><b>${e.tm}</b></div>`:""}</div>`:""}<div class="row"><a class="btn" href="#" data-reg data-ev="${e.n}">Register</a><button class="btn alt" data-det="${i}-${k}">Details</button></div></div>`};
const catHTML=i=>{const c=CATS[i];return `<div class="subhead">${c.n} events</div><div class="subs">`+c.ev.map((e,k)=>evCard(i,k)).join("")+"</div>"};
function openAll(){if(typeof resetFlt==="function")resetFlt();$$(".cat").forEach(b=>b.setAttribute("aria-expanded","true"));openC=-2;$("#subs").innerHTML=CATS.map((c,i)=>catHTML(i)).join("");applyForm();$("#subwrap").classList.add("open")}
const mb=$("#more"),nv=$("#nav");
function menu(o){nv.classList.toggle("open",o);$("#scrim").classList.toggle("open",o);mb.setAttribute("aria-expanded",String(o))}
mb.addEventListener("click",e=>{e.stopPropagation();menu(!nv.classList.contains("open"))});
function applyForm(){if(!GFORM_URL)return;$$("a[data-reg]").forEach(a=>{a.href=GFORM_URL;a.target="_blank";a.rel="noopener"})}
function openCat(i){const w=$("#subwrap");if(typeof resetFlt==="function")resetFlt();$$(".cat").forEach(b=>b.setAttribute("aria-expanded",String(+b.dataset.cat===i&&openC!==i)));
 if(openC===i){w.classList.remove("open");openC=-1;return}
 openC=i;const c=CATS[i];
 $("#subs").innerHTML=catHTML(i);
 applyForm();w.classList.add("open");setTimeout(()=>$("#subs").scrollIntoView({behavior:"smooth",block:"center"}),450)}

/* search + category filter */
const flt={q:"",c:-1};
function evHay(i,k){const e=CATS[i].ev[k];return [e.n,e.g,CATS[i].n,e.t,e.v,e.d,e.tm,JSON.stringify([e.fc||"",e.sc||""])].filter(Boolean).join(" ").toLowerCase()}
function chipsDraw(){const el=$("#evcat");el.innerHTML=`<option value="-1">All categories</option>`+CATS.map((c,i)=>`<option value="${i}">${c.n} (${c.ev.length})</option>`).join("");el.value=String(flt.c)}
function resetFlt(){flt.q="";flt.c=-1;const q=$("#evq");if(q)q.value="";chipsDraw();$("#sres").classList.remove("open");fsig=""}
let fsig="";
function runFlt(scroll){const w=$("#sres");const toks=flt.q.toLowerCase().split(/\s+/).filter(Boolean);
 if(!toks.length&&flt.c<0){w.classList.remove("open");fsig="";return}
 let out="",n=0,sig="";
 CATS.forEach((c,i)=>{if(flt.c>=0&&flt.c!==i)return;const hit=[];c.ev.forEach((e,k)=>{const h=evHay(i,k);if(toks.every(t=>h.includes(t)))hit.push(k)});
  if(hit.length){n+=hit.length;sig+=i+":"+hit.join(",")+";";out+=`<div class="subhead">${c.n} events</div><div class="subs">`+hit.map((k,j)=>evCard(i,k,j)).join("")+"</div>"}});
 $("#rescount").innerHTML=toks.length?`${n} event${n===1?"":"s"} found for “${flt.q.trim().replace(/</g,"&lt;")}”`:`${n} event${n===1?"":"s"} in ${CATS[flt.c].n}`;
 $$(".cat").forEach(b=>b.setAttribute("aria-expanded","false"));$("#subwrap").classList.remove("open");openC=-1;
 if(!sig)sig="none";if(sig!==fsig){fsig=sig;$("#resbody").innerHTML=n?out:`<p class="nores">No events match your search. Try another word or choose All categories.</p>`;applyForm()}
 const was=w.classList.contains("open");w.classList.add("open");
 if(!was||scroll){const r=$(".evtools").getBoundingClientRect(),off=parseInt(getComputedStyle(document.documentElement).scrollPaddingTop)||96;
  if(r.top<off||r.top>off+140)scrollTo({top:scrollY+r.top-off-10,behavior:"smooth"})}}
chipsDraw();
$("#evq").addEventListener("input",e=>{flt.q=e.target.value;runFlt(false)});
$("#evcat").addEventListener("change",e=>{flt.c=+e.target.value;runFlt(true)});
let lastF=null;
function showDet(i,k){const e=CATS[i].ev[k];lastF=document.activeElement;$("#mc").textContent=CATS[i].n.toUpperCase()+" EVENT";$("#mt").textContent=e.n;$("#mp").textContent=e.a;
 $("#mm").innerHTML=[e.g,e.t].filter(Boolean).map(x=>`<span class="chip">${x}</span>`).join("");
 $("#ml").innerHTML=(e.r||RULES).map(r=>r.startsWith("##")?`<li class="sec">${r.slice(2)}</li>`:`<li>${r}</li>`).join("");
 $("#mf").innerHTML=e.f?`<div class="fee"><span>ENTRY FEE</span><b>${e.f[0]}</b><em>${e.f[1]}</em></div>`:"";
 const L=x=>Array.isArray(x[0])?x:[x];
 const tl=p=>{const d=p.replace(/\D/g,"");return `<a href="tel:+${d.length===10?"91"+d:d}">${p}</a>`};
 $("#mi").innerHTML=(e.d?`<div><dt>Date</dt><dd>${e.d}</dd></div>`:"")+(e.tm?`<div><dt>Time</dt><dd>${e.tm}</dd></div>`:"")+(e.x||[]).map(x=>`<div><dt>${x[0]}</dt><dd>${x[1]}</dd></div>`).join("")+(e.v?`<div class="w"><dt>Venue</dt><dd>${e.v}</dd></div>`:"")+(e.fc?`<div class="w"><dt>Faculty coordinator${L(e.fc).length>1?"s":""}</dt><dd>${L(e.fc).map(x=>x[0]+(x[1]?` (${tl(x[1])})`:"")).join("<br>")}</dd></div>`:"")+(e.sc?`<div class="w"><dt>Student coordinator${L(e.sc).length>1?"s":""}</dt><dd>${L(e.sc).map(x=>x[0]+(x[1]?` (${tl(x[1])})`:"")).join("<br>")}</dd></div>`:"");
 $("#mrh").textContent=e.r&&!e.r[0].startsWith("##")?"Rules and regulations":"";$("#mnote").style.display=e.r?"none":"";$("#mreg").dataset.ev=e.n;applyForm();
 $("#modal").classList.add("open");$("#modal").setAttribute("aria-hidden","false");$(".x").focus()}
function closeDet(){$("#modal").classList.remove("open");$("#modal").setAttribute("aria-hidden","true");if(lastF)lastF.focus()}
document.addEventListener("click",e=>{
 if(!e.target.closest("#bbtn"))bmenu(false);
 if(e.target.closest('nav a[href="#events"],.fnav a[href="#events"]'))openAll();
 if(!e.target.closest("#more"))menu(false);
 const rg=e.target.closest("[data-reg]");if(rg&&!GFORM_URL){e.preventDefault();toast("The registration Google Form link will be added here soon")}
 const t=e.target.closest("[data-d]");if(t)draw(t.dataset.d);
 const c=e.target.closest("[data-cat]");if(c)openCat(+c.dataset.cat);
 const d=e.target.closest("[data-det]");if(d){const p=d.dataset.det.split("-");showDet(+p[0],+p[1])}
 if(e.target.closest(".x")||e.target===$("#modal")||e.target.closest("#mreg"))closeDet()});
addEventListener("keydown",e=>{if(e.key==="Escape"){closeDet();menu(false);bmenu(false);bview(false)}});
applyForm();
const bd=$("#bdrop"),bb=$("#bbtn");
function bmenu(o){bd.classList.toggle("open",o);bb.setAttribute("aria-expanded",String(o))}
bb.addEventListener("click",e=>{e.stopPropagation();bmenu(!bd.classList.contains("open"))});
function bview(o){$("#bmodal").classList.toggle("open",o);$("#bmodal").setAttribute("aria-hidden",String(!o));if(o)$(".bx").focus()}
$("#bview").addEventListener("click",()=>bview(true));
$(".bx").addEventListener("click",()=>bview(false));
$("#bmodal").addEventListener("click",e=>{if(e.target===$("#bmodal"))bview(false)});
function toast(m){const x=$("#toast");x.textContent=m;x.classList.add("on");setTimeout(()=>x.classList.remove("on"),2800)}
$$("[data-dl]").forEach(el=>el.addEventListener("click",async e=>{if(!window.claude)return;e.preventDefault();
 try{const d=await claude.use("downloads");if(!d){toast("Download is not available in this view");return}
  const b=atob(el.href.split(",")[1]),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);
  await d.save({filename:"VYBE2K26-Brochure.pdf",data:u})}catch(x){if(!x||x.code!=="declined")toast("Could not save the brochure")}}));
const cio=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;cio.unobserve(e.target);const el=e.target,n=+el.dataset.n,t0=performance.now();(function s(t){const p=Math.min((t-t0)/1500,1);el.textContent=Math.round(n*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(s)})(t0)}),{threshold:.6});
$$("[data-n]").forEach(e=>cio.observe(e));
function draw(d){$$(".tabs button").forEach(b=>b.classList.toggle("on",b.dataset.d===String(d)));$("#slots").innerHTML=SCH[d].map((g,i)=>`<div class="slot" style="--i:${i}"><b>${g[0]}</b><div>${g[1].map(x=>`<div class="se"><strong>${x.n}</strong>${x.c?` <em>${x.c}</em>`:""}${x.s?`<span>${x.s}</span>`:""}</div>`).join("")}</div></div>`).join("")}
draw(1);
function ok(f,m,msg){f.addEventListener("submit",e=>{e.preventDefault();m.style.display="block";m.textContent=msg(f.n.value,f);f.reset()})}
/* title letters */
/* countdown */
const T=new Date("2026-11-04T09:00:00+05:30");
function cd(){let s=Math.max(0,(T-new Date())/1000|0);const v=[["DAYS",s/86400|0],["HOURS",s/3600%24|0],["MINS",s/60%60|0],["SECS",s%60]];
 $("#cd").innerHTML=s?v.map(x=>`<div><b>${String(x[1]).padStart(2,"0")}</b><small>${x[0]}</small></div>`).join(""):"<div style='padding:10px 20px'>The fest is live!</div>"}
cd();setInterval(cd,1000);
/* reveal, scroll-spy */
const rio=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("in");rio.unobserve(e.target)}}),{threshold:.15});
$$(".rv,.bar").forEach(e=>rio.observe(e));
const links=$$("nav a");
const sio=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.target.id!=="stats")links.forEach(l=>l.classList.toggle("on",l.getAttribute("href")==="#"+e.target.id))}),{rootMargin:"-40% 0px -55% 0px"});
$$("main section").forEach(s=>sio.observe(s));
/* parallax background + progress + petal speed */
let vy=0,last=scrollY;
addEventListener("scroll",()=>{const y=scrollY;$("#bg").style.transform=`translateY(${-y*.06}px) scale(${1+Math.min(y/8000,.12)})`;
 $("#prog").style.width=(y/(document.body.scrollHeight-innerHeight)*100)+"%";vy=y-last;last=y},{passive:true});
/* 3D tilt */
const t3=$("#t3d");
document.addEventListener("mousemove",e=>{const x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;t3.style.transform=`rotateY(${x*8}deg) rotateX(${-y*6}deg)`});
$$(".tilt").forEach(c=>{c.addEventListener("mousemove",e=>{const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`rotateY(${x*14}deg) rotateX(${-y*14}deg)`});c.addEventListener("mouseleave",()=>c.style.transform="")});
/* desktop page transition (menu / footer / hero links) */
const wipe=$("#wipe"),deskMQ=matchMedia("(min-width:769px)"),rmMQ=matchMedia("(prefers-reduced-motion:reduce)");let wbusy=false;
document.addEventListener("click",e=>{
 const a=e.target.closest('a[href^="#"]');if(!a)return;const h=a.getAttribute("href");
 if(h.length<2||a.hasAttribute("data-reg")||!deskMQ.matches||rmMQ.matches)return;
 const tg=document.getElementById(h.slice(1));if(!tg)return;
 e.preventDefault();if(wbusy)return;wbusy=true;wipe.classList.add("on");
 setTimeout(()=>{const off=parseInt(getComputedStyle(document.documentElement).scrollPaddingTop)||96;
  scrollTo({top:tg.getBoundingClientRect().top+scrollY-off+1,behavior:"instant"});
  setTimeout(()=>{wipe.classList.remove("on");wbusy=false},140)},330)});
